### ISSUE TITLE
create dataset

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-dataset-cli#7]
@emilymcafee is there an API endpoint for creating datasets?

**Comment by emilymcafee** [comment]
@tmcw yes, this hasn't been documented yet but will be shortly.

[The endpoint](https://github.com/mapbox/api-core/blob/master/servers/api.js#L1588) for creating a dataset is `POST datasets/v1/:account`. It needs a token with `map:write` scope.

It uses [this function](https://github.com/mapbox/mapbox-core/blob/master/lib/datasets.js#L58).

**Comment by tmcw** [comment]
Done in a072fccf5fff5bb776e67dd3c4fcd1cfc765b65a
