### ISSUE TITLE
list datasets

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-dataset-cli#8]
@emilymcafee is this part of the default /api/Maps call, or is there another way to learn of a user's datasets?

**Comment by emilymcafee** [comment]
Again, not documented yet but will be shortly.

[The endpoint](https://github.com/mapbox/api-core/blob/master/servers/api.js#L1590) for listing a user's datasets is `GET /datasets/v1/:account`. It needs a token with `map:read` scope.

It uses [this function](https://github.com/mapbox/mapbox-core/blob/master/lib/datasets.js#L94).
